# Generated by Django 3.1.7 on 2021-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210318_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='picture',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
