# Generated by Django 3.1.7 on 2021-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210318_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
